"""add service requests

Revision ID: 2f328d83af51
Revises: 7d10d875a283
Create Date: 2025-12-24 18:38:29.621164

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f328d83af51'
down_revision = '7d10d875a283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('OPEN', 'CANCELLED', 'ACCEPTED', 'COMPLETED', name='request_status'),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('OPEN', 'CANCELLED', 'ACCEPTED', 'COMPLETED', name='request_status'),
               existing_nullable=False)

    # ### end Alembic commands ###
