"""add sitter profiles

Revision ID: 4864f9e2494e
Revises: cc14d61b9f11
Create Date: 2025-12-30 18:13:49.903988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4864f9e2494e'
down_revision = 'cc14d61b9f11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('reviews_booking_id_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_reviews_booking_id'), ['booking_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_reviews_sitter_id'), ['sitter_id'], unique=False)

    with op.batch_alter_table('sitter_profiles', schema=None) as batch_op:
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column(
              "services",
              existing_type=sa.ARRAY(sa.String()),  # prior type was varchar[]
              type_=sa.JSON(),
              postgresql_using="to_json(services)"   )
        batch_op.alter_column('base_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('is_available',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('verification_status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.drop_constraint('sitter_profiles_sitter_id_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_sitter_profiles_sitter_id'), ['sitter_id'], unique=True)
        batch_op.drop_column('avg_rating')
        batch_op.drop_column('trust_score')
        batch_op.drop_column('reviews_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sitter_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviews_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('trust_score', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('avg_rating', sa.NUMERIC(precision=3, scale=2), server_default=sa.text('0.0'), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_sitter_profiles_sitter_id'))
        batch_op.create_unique_constraint('sitter_profiles_sitter_id_key', ['sitter_id'])
        batch_op.alter_column('verification_status',
               existing_type=sa.String(length=50),
               type_=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_available',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('base_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('services',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_sitter_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_booking_id'))
        batch_op.create_unique_constraint('reviews_booking_id_key', ['booking_id'])

    # ### end Alembic commands ###
