"""initial schema 

Revision ID: 7d10d875a283
Revises: 
Create Date: 2025-12-22 10:54:01.359307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d10d875a283'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'SITTER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('city', sa.Enum('Tunis', 'Ariana', 'Ben_Arous', 'Manouba', 'La_Marsa', 'Carthage', 'Sidi_Bou_Said', 'Menzah', name='grand_tunis_city'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
